services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${PG_PORT:-5433}:5432"  # host:container; override PG_PORT in .env if 5433 is taken
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
  web-build:
    image: node:20-bullseye
    working_dir: /app
    profiles:
      - build
    volumes:
      - ./apps/web:/app
      - web-build-node_modules:/app/node_modules
      - web-build-npm-cache:/root/.npm

volumes:
  web-build-node_modules:
  web-build-npm-cache:
