[phases.setup]
  nixPkgs = ["python311Full", "nodejs_20"]

  [phases.install]
  cmds = [
    "pip install -r requirements.txt",
    "npm --prefix web ci"
  ]

  [phases.build]
  cmds = [
    "npm --prefix web run build",
    "PYTHONPATH=. python -m alembic upgrade head"
  ]

  [start]
  cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"