[phases.setup]
nixPkgs = ["python311Full", "nodejs_20"]

[phases.install]
# Extend the default install steps (creates venv + pip install) and then run npm ci
cmds = ["...", "npm --prefix web ci"]

[phases.build]
cmds = ["npm --prefix web run build",]


[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
